# Multi-Variable linear regression

소스 코드 출처:

https://github.com/hunkim/DeepLearningZeroToAll/

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.set_random_seed(11)

실제 데이터

In [3]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.] # float형태를 위해, 소수점을 표시

데이터들을 담을 그릇을 만든다

In [6]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

텐서플로우 기초(linear regression)
https://github.com/YBIGTA/Deep_learning/blob/master/RNN/nlp/%EA%B5%AC%ED%98%84/%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C%EC%9A%B0%20%EA%B8%B0%EC%B4%88(linear%20regression).ipynb

위의 글에서 w가 등장했었다.

w는 가중치(weight)이다. w1은 x1의 가중치인 식이다.

가중치를 처음 들어봤다면 감이 오지 않을 것이다...

가중치는 말 그대로 중요하게 생각하는 것이다!

x1의 가중치인 w1가 크다면 x1인 결과값 y가 나오는데 큰 역할을 한다는 뜻이고, x2의 가중치인 w2가 작다면 결과값 y가 나오는데 작은 역할을 한다는 뜻이다.

아래 과정은 그러한 가중치들을 담을 그릇들을 만드는 과정이다.

b는 bias로 그래프를 좀 더 다양한 위치에 있게 해준다. 만약 b가 없다면 반드시 원점을 지나야만 하는 그래프밖에 그리지 못할 것이다...!

In [7]:
w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = w1 * x1 + w2 * x2 + w3 * x3 + b

In [8]:
# cost/Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize function
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

밑의 코드에서 '_'처리를 한 것은 변수로 쓰지 않지만 train도 run을 해야 train이 되기 때문에 한꺼번에 돌리때 저렇게 표시를 해줘야 된다.

In [10]:
# Make Session
sess = tf.Session()
# Initialize Variables
sess.run(tf.global_variables_initializer())
for step in range(20001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    
    if step % 5000 == 0:
        print('step:', step, 'w1:', sess.run(w1), 'w2:', sess.run(w2), 'w3:', sess.run(w3), 'b:', sess.run(b), 'cost:', cost_val) 
    

step: 0 w1: [ 1.64843261] w2: [-1.07085955] w3: [ 0.01008558] b: [ 1.70012081] cost: 46188.5
step: 5000 w1: [ 1.38776541] w2: [ 0.26680243] w3: [ 0.34001312] b: [ 1.69697511] cost: 2.41367
step: 10000 w1: [ 1.18520749] w2: [ 0.48417085] w3: [ 0.32563618] b: [ 1.69268703] cost: 0.384368
step: 15000 w1: [ 1.11965823] w2: [ 0.53361291] w3: [ 0.34163955] b: [ 1.68984389] cost: 0.226966
step: 20000 w1: [ 1.09096873] w2: [ 0.54049176] w3: [ 0.36323231] b: [ 1.68758035] cost: 0.198952


In [15]:
# Make Session
sess = tf.Session()
# Initialize Variables
sess.run(tf.global_variables_initializer())
for step in range(20001):
    sess.run(train, feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    
    if step % 100 == 0:
        print('step:', step, 'w1:', sess.run(w1), 'w2:', sess.run(w2), 'w3:', sess.run(w3), 'b:', sess.run(b), 'cost:', sess.run(cost)) 

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'Placeholder', defined at:
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-e108970238bc>", line 1, in <module>
    x1 = tf.placeholder(tf.float32)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1530, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1954, in _placeholder
    name=name)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]


- Q1. 왜 바로 위의 코드처럼 선형회귀 때 같이 식을 단순하게 짠다면 오류가 생기는 것일까? 
- Q2. 왜 x1과 x1_data를 구분하여 feed 시키는 형태로 식을 짠 것일까? 

# (번외2) Tensorflow를 활용한 Multi-Variable linear regression(Matrix 계산)

In [2]:
tf.set_random_seed(12)

위에서는 x1_data, x2_data 이런 식으로 x데이터를 일일이 나눠줘야 했다. 

지금 우리가 data를 쓰는 방식도 번거롭지만 위의 과정이 더 번거롭다...

이왕이면 덜 번거로운 걸 쓰는 게 좋지 않은가?

이제는 굳이 x_data를 split하지 않고 한꺼번에 묶어서 표현해줄 것이다.

In [3]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]] # rank2, 5X3 matrix
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]] # rank2, 5X1 matrix

In [4]:
X = tf.placeholder(tf.float32, shape=[None, 3]) #n행 3열
Y = tf.placeholder(tf.float32, shape=[None, 1]) #n행 1열

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [5]:
hypothesis = tf.matmul(X, W) + b

In [6]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [7]:
sess = tf.InteractiveSession()

# 번외편: Optimizer 비교

- 변수가 1개 있는 linear regression에서 맛보기로 opimizer를 비교했었다.
- 비록 해당 모델에서는 아주 기본적인 GradientDescent optimizer가 가장 안정적으로 로스를 줄였지만, 실제 쓰이는 모델과 흡사한 이번 모델에서는 그렇지 않을 것이다!
- 최적의 결과를 위해 각 optimizer 별로 learing rate를 다르게 줬다.

## GradientDescent 

In [13]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)

train = optimizer.minimize(cost)

In [14]:
sess.run(tf.global_variables_initializer())
for step in range(20001):
    cost_val, hypo_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step%5000 == 0:
        print("step:", step, "cost:", cost_val, "\npredicting y:\n", hypo_val)

step: 0 cost: 22318.7 
predicting y:
 [[ 15.71236992]
 [ 27.03840446]
 [ 21.9840374 ]
 [ 29.31786919]
 [ 18.24395561]]
step: 5000 cost: 6.0748 
predicting y:
 [[ 149.14860535]
 [ 185.77845764]
 [ 179.29698181]
 [ 199.88243103]
 [ 139.53625488]]
step: 10000 cost: 4.78362 
predicting y:
 [[ 149.55827332]
 [ 185.55271912]
 [ 179.49267578]
 [ 199.47897339]
 [ 139.70001221]]
step: 15000 cost: 3.78564 
predicting y:
 [[ 149.82077026]
 [ 185.42163086]
 [ 179.63528442]
 [ 199.09936523]
 [ 139.93547058]]
step: 20000 cost: 3.00363 
predicting y:
 [[ 150.02737427]
 [ 185.32325745]
 [ 179.75361633]
 [ 198.75737   ]
 [ 140.16734314]]


기본템(?)답게 기대할 만한 결과가 나오지 않았다.

## Adam 

In [25]:
optimizer = tf.train.AdamOptimizer(learning_rate=0.1)

train = optimizer.minimize(cost)

In [26]:
sess.run(tf.global_variables_initializer())
for step in range(20001):
    cost_val, hypo_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step%5000 == 0:
        print("step:", step, "cost:", cost_val, "\npredicting y:\n", hypo_val)

step: 0 cost: 271.968 
predicting y:
 [[ 139.07672119]
 [ 165.86231995]
 [ 164.31846619]
 [ 175.81037903]
 [ 128.84529114]]
step: 5000 cost: 0.294461 
predicting y:
 [[ 151.28121948]
 [ 184.13693237]
 [ 180.14515686]
 [ 195.60662842]
 [ 141.8130188 ]]
step: 10000 cost: 0.106998 
predicting y:
 [[ 151.70661926]
 [ 184.51701355]
 [ 180.36421204]
 [ 196.19281006]
 [ 142.21405029]]
step: 15000 cost: 0.126461 
predicting y:
 [[ 151.85844421]
 [ 184.65953064]
 [ 180.45732117]
 [ 196.40003967]
 [ 142.35661316]]
step: 20000 cost: 0.104352 
predicting y:
 [[ 151.73352051]
 [ 184.49739075]
 [ 180.28315735]
 [ 196.24264526]
 [ 142.24305725]]


역시 널리 쓰이는 optimizer답게 가장 많이 cost를 낮추었다.

## Adadelta

In [33]:
optimizer = tf.train.AdadeltaOptimizer(learning_rate=0.1)

train = optimizer.minimize(cost)

In [34]:
sess.run(tf.global_variables_initializer())
for step in range(20001):
    cost_val, hypo_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step%5000 == 0:
        print("step:", step, "cost:", cost_val, "\npredicting y:\n", hypo_val)

step: 0 cost: 4909.25 
predicting y:
 [[  86.56267548]
 [ 111.34281158]
 [ 105.30742645]
 [ 120.68418121]
 [  82.10546112]]
step: 5000 cost: 8.66801 
predicting y:
 [[ 148.76152039]
 [ 185.96566772]
 [ 178.88311768]
 [ 200.72814941]
 [ 139.11608887]]
step: 10000 cost: 4.79292 
predicting y:
 [[ 149.63056946]
 [ 185.5090332 ]
 [ 179.28436279]
 [ 199.58049011]
 [ 139.81843567]]
step: 15000 cost: 1.82923 
predicting y:
 [[ 150.49668884]
 [ 185.07795715]
 [ 179.688797  ]
 [ 198.27262878]
 [ 140.72782898]]
step: 20000 cost: 0.72964 
predicting y:
 [[ 151.01219177]
 [ 184.81617737]
 [ 179.89581299]
 [ 197.47119141]
 [ 141.3192749 ]]


그렇게 좋지도 나쁘지도 않은 결과가 나왔다.

## Momentum

In [62]:
optimizer = tf.train.MomentumOptimizer(0.1e-4, 0.5)

train = optimizer.minimize(cost)

In [63]:
sess.run(tf.global_variables_initializer())
for step in range(20001):
    cost_val, hypo_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step%5000 == 0:
        print("step:", step, "cost:", cost_val, "\npredicting y:\n", hypo_val)

step: 0 cost: 33521.2 
predicting y:
 [[ 321.00518799]
 [ 374.96994019]
 [ 375.11929321]
 [ 407.03359985]
 [ 284.64572144]]
step: 5000 cost: 0.256929 
predicting y:
 [[ 152.0496521 ]
 [ 184.27786255]
 [ 180.78564453]
 [ 196.15779114]
 [ 141.65567017]]
step: 10000 cost: 0.151614 
predicting y:
 [[ 151.60916138]
 [ 184.57873535]
 [ 180.64900208]
 [ 196.07022095]
 [ 142.04142761]]
step: 15000 cost: 0.150933 
predicting y:
 [[ 151.57632446]
 [ 184.60037231]
 [ 180.63757324]
 [ 196.07090759]
 [ 142.06271362]]
step: 20000 cost: 0.150765 
predicting y:
 [[ 151.5715332 ]
 [ 184.60296631]
 [ 180.63493347]
 [ 196.07621765]
 [ 142.06045532]]


꽤 괜찮은 성적이다.

그리고 또 한가지 놀라운 점은 cost가 3만대에서 소수점까지 떨어진 것이다.

정말 무서운 속도를 보여준다.

## RMSprop

In [107]:
optimizer = tf.train.RMSPropOptimizer(1e-3)

train = optimizer.minimize(cost)

In [108]:
sess.run(tf.global_variables_initializer())
for step in range(20001):
    cost_val, hypo_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step%5000 == 0:
        print("step:", step, "cost:", cost_val, "\npredicting y:\n", hypo_val)

step: 0 cost: 186848.0 
predicting y:
 [[-225.23104858]
 [-280.984375  ]
 [-271.49563599]
 [-296.89306641]
 [-215.77656555]]
step: 5000 cost: 0.164617 
predicting y:
 [[ 151.80441284]
 [ 184.25289917]
 [ 180.45388794]
 [ 195.85705566]
 [ 142.01495361]]
step: 10000 cost: 0.141066 
predicting y:
 [[ 151.57997131]
 [ 184.39503479]
 [ 180.3800354 ]
 [ 195.90640259]
 [ 142.09866333]]
step: 15000 cost: 0.137832 
predicting y:
 [[ 151.5606842 ]
 [ 184.40396118]
 [ 180.36326599]
 [ 195.94456482]
 [ 142.07658386]]
step: 20000 cost: 0.135753 
predicting y:
 [[ 151.556427  ]
 [ 184.4052124 ]
 [ 180.34907532]
 [ 195.96372986]
 [ 142.07118225]]


Adam 다음으로 성적이 제일 좋다.

Adadelta와 비슷하지만 훨씬 잘 나온다.

## Adagrad

In [127]:
optimizer = tf.train.AdagradOptimizer(0.75)

train = optimizer.minimize(cost)

In [128]:
sess.run(tf.global_variables_initializer())
for step in range(20001):
    cost_val, hypo_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step%5000 == 0:
        print("step:", step, "cost:", cost_val, "\npredicting y:\n", hypo_val)

step: 0 cost: 3985.14 
predicting y:
 [[ 200.37942505]
 [ 256.36105347]
 [ 244.3614502 ]
 [ 268.87619019]
 [ 197.13059998]]
step: 5000 cost: 0.627546 
predicting y:
 [[ 150.87504578]
 [ 184.94134521]
 [ 180.04702759]
 [ 197.26025391]
 [ 141.47244263]]
step: 10000 cost: 0.242812 
predicting y:
 [[ 151.36668396]
 [ 184.6741333 ]
 [ 180.12792969]
 [ 196.80993652]
 [ 141.81448364]]
step: 15000 cost: 0.143088 
predicting y:
 [[ 151.56314087]
 [ 184.57539368]
 [ 180.15412903]
 [ 196.56474304]
 [ 142.04016113]]
step: 20000 cost: 0.116664 
predicting y:
 [[ 151.66223145]
 [ 184.52592468]
 [ 180.16911316]
 [ 196.43756104]
 [ 142.15628052]]


선형 모델에 적합한 특징답게, 선형 모델에서 우수한 성적이 나온다.

거의 Adam과 비슷하다.

한 가지 주의점은 optimizer별로 잘 되는 learing rate가 다르니 0.1씩이나 0.05씩 값을 조정해나가면서 찾는 게 좋은 것 같다.