작성자 : 노혜미 박승리 (YBIGTA 10기)

# (번외 1-1) Tensorflow를 활용한 Multi-Variable linear regression

In [1]:
import tensorflow as tf
import numpy as np
import time # 계산시간 측정

In [2]:
tf.set_random_seed(11)

In [3]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.] # float형태를 위해, 소수점을 표시

In [4]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [5]:
w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = w1 * x1 + w2 * x2 + w3 * x3 + b

cost는 우리가 세운 가설(y 추정치)에서 실제 Y값을 뺀 것에 제곱을 한 뒤, 각각을 모두 더하고 이에 대한 평균을 내겠다는 것이다.

우리가 세운 가설이 실제 Y값과 비슷하다면 제곱되는 수의 크기가 작으므로 cost는 작아질 것이고 반대라면 cost가 커질 것이다.

In [6]:
# cost/Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize function
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

실행시키기 전에 반드시 tf.global_variables_initializer()로 초기화를 해줘야 에러가 나지 않는다.

with tf.Session() as sess과 같이 쓴 이유는 session은 열고 닫는 과정을 거쳐야 되는데 저렇게 쓰게 되면 일일이 세션을 열고 닫지 않아도 된다!

밑에서 '_'과 뭔지 궁금할 수 있을 것이다.

_에 해당하는 것은 train이다. train의 값은 run을 해줘야 하지만 우리가 나중에 print를 한다든지 쓸 값이 아니다.

그래서 한꺼번에 run 해줄 때,cost와 hypothesis는 쓰지만 train은 쓰지 않으므로 '_'를 쓴 것이다.

In [8]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    t1 = time.time()
    
    for step in range(20001):
        cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    
        if step % 5000 == 0:
            print('step:', step, 'cost:', cost_val, '\npredicted Y:\n', hy_val) 
    t2 = time.time()
    print(t2-t1)

step: 0 cost: 40421.7 
predicted Y:
 [-24.11546707 -31.62531281 -29.64182472 -33.68144608 -23.71737099]
step: 5000 cost: 0.421932 
predicted Y:
 [ 152.31440735  184.11781311  181.01208496  195.97280884  141.54447937]
step: 10000 cost: 0.211829 
predicted Y:
 [ 151.79940796  184.46759033  180.84992981  195.88818359  141.97621155]
step: 15000 cost: 0.194538 
predicted Y:
 [ 151.65719604  184.56214905  180.80245972  195.88285828  142.07614136]
step: 20000 cost: 0.190783 
predicted Y:
 [ 151.61230469  184.59034729  180.78523254  195.89613342  142.09172058]
13.94911527633667


In [10]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(20001):
        sess.run(train, feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    
    if step % 100 == 0:
        print('step:', step, 'w1:', sess.run(w1), 'w2:', sess.run(w2), 'w3:', sess.run(w3), 'b:', sess.run(b), 'cost:', sess.run(cost)) 

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'Placeholder', defined at:
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-e108970238bc>", line 1, in <module>
    x1 = tf.placeholder(tf.float32)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1530, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1954, in _placeholder
    name=name)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\PARK SEONGRI\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]


- Q1. 왜 바로 위의 코드처럼 선형회귀 때 같이 train만 세션을 실행한다면 오류가 생기는 것일까? 
- Q2. 왜 x1과 x1_data를 구분하여 feed 시키는 형태로 식을 짠 것일까? 

# (번외 1-2) Tensorflow를 활용한 Multi-Variable linear regression(Matrix 계산)

In [9]:
tf.set_random_seed(12)

In [26]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]] # rank2, 5X3 matrix
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]] # rank2, 5X1 matrix

In [27]:
X = tf.placeholder(tf.float32, shape = [None, 3]) # None : n개, 여기서는 5개
Y = tf.placeholder(tf.float32, shape = [None, 1])

In [28]:
W = tf.Variable(tf.random_normal([3,1]), name = 'weight') # 3은 input의 개수, 1은 output의 개수
b = tf.Variable(tf.random_normal([1]), name = 'bias') # bias의 output개수는 Y의 output의 개수와 같아야 한다.

In [29]:
hypothesis = tf.matmul(X,W) + b

In [30]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [15]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [16]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    t1 = time.time()
    
    for step in range(20001):
        cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X : x_data, Y : y_data})
        if step % 5000 == 0:
            print('step:', step, 'cost:', cost_val, '\npredicted Y:\n', hy_val )
            
    t2 = time.time()
    print(t2-t1)

step: 0 cost: 178397.0 
predicted Y:
 [[-217.4924469 ]
 [-269.71856689]
 [-261.45748901]
 [-286.00027466]
 [-206.5461731 ]]
step: 5000 cost: 1.17618 
predicted Y:
 [[ 153.06187439]
 [ 183.58607483]
 [ 181.06736755]
 [ 196.37693787]
 [ 140.78640747]]
step: 10000 cost: 0.213609 
predicted Y:
 [[ 151.97612   ]
 [ 184.32965088]
 [ 180.73358154]
 [ 196.14303589]
 [ 141.75605774]]
step: 15000 cost: 0.149349 
predicted Y:
 [[ 151.69386292]
 [ 184.52246094]
 [ 180.64611816]
 [ 196.08659363]
 [ 142.00354004]]
step: 20000 cost: 0.144908 
predicted Y:
 [[ 151.61914062]
 [ 184.57307434]
 [ 180.62232971]
 [ 196.07546997]
 [ 142.06503296]]
10.901878833770752


Matrix계산 시간이 조금 더 적게 걸렸다.

더 많은 데이터일 경우 확연하게 차이가 날 것이다.

# (번외 1-3) Tensorflow를 활용한 Logistic Regression

- logistic regression은 input이 들어왔을 때, 결과가 0이냐 1이냐를 판단하는 모델이다.

In [17]:
tf.set_random_seed(13)

In [18]:
x_data = [[1, 2],
          [2, 3],
          [3, 1],
          [4, 3],
          [5, 3],
          [6, 2]]
y_data = [[0],
          [0],
          [0],
          [1],
          [1],
          [1]] # 0 or 1 binary data

In [19]:
X = tf.placeholder(tf.float32, shape = [None, 2])
Y = tf.placeholder(tf.float32, shape = [None, 1])

In [20]:
W = tf.Variable(tf.random_normal([2,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

이쯤에서 의문이 드는 게 placeholder와 Variable의 차이일 것이다.

두 개 모두 변수를 담는 그릇이지만 조금 다르다.

placeholder에는 실제 training data를 넣는다. 

Variable에는 weight와 bias를 넣는다.

즉, placeholder에는 update가 필요없는 data가 들어가는 것이고 variable에는 update가 필요한 data가 들어가는 것이다.

In [21]:
hypothesis = tf.sigmoid(tf.matmul(X,W) + b)
# tf.div(1., 1. + tf.exp(tf.matmul(X,W) + b))

cost 함수가 이렇게 되는 이유는 그래프를 통해 살펴보는 것이 이해가 더 쉬울 것이다.

![cost](http://adit.io/imgs/logistic/log_graph.png)
이미지 출처: http://adit.io/posts/2016-03-13-Logistic-Regression.html

왼쪽 그래프 y = -logx , 오른쪽 그래프 y = -log(1-x)

여기서 x는 예측 값(hypothesis)가 되고, y는 실제 값(Y)가 된다. (your prediction에서 100%에 해당하는 x 값이 1이다.)

만약 실제 값이 1인데, 예측값을 0이라고 했다면 우리는 cost를 쎄게 줘서 모델에게 잘못 예측을 했다는 것을 알려야 된다.

반대로 실제 값이 1일 때, 예측값을 1이라고 했다면 모델이 정확한 것이므로 cost를 줄 필요가 없다. (cost를 모델에게 주는 벌(?)로 이해하면 되겠다.)

위의 그래프는 이러한 상황을 그대로 반영했다.

실제 값이 1일 때, 예측 값이 0에 가까우면 cost가 발산하고 1에 가까우면 cost는 거의 0에 수렴한다.

실제 값이 0일 때는 정 반대이다.

cost함수에서 log함수 앞에 Y를 붙인 이유는 Y가 1일때는 왼쪽 그래프만 고려하면 되고, Y가 0일때는 오른쪽 그래프만 고려하면 되기 때문이다.

Y=0일때 왼쪽 함수 값은 0이 곱해지기 때문에 없어지고 Y=1일때는 오른쪽 함수 값이 없어진다.

(밑의 cost 함수를 보면 -log가 아닌데 맨 앞으로 -를 빼냈다.)

In [22]:
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

In [23]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-03)
train = optimizer.minimize(cost)

In [24]:
# hypothesis > 0.5이면 T, < 0.5이면 F이고 이를 float32 dtype으로 바꾸면 1, 0이 된다.
# 보통 1을 True로, 0을 False로 생각한다. 그래서 이의 중간 값이 0.5를 기준으로 한 것이다.
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)

# predicted == Y 이면 T, 아니면 F이고 이를 1, 0으로 바꾼다.
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32)) 

In [25]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(20001):
        cost_val, pre, _ = sess.run([cost, predicted, train], feed_dict = {X : x_data, Y : y_data})
        if step % 5000 == 0:
            print('step:', step, "cost:", cost_val, "\npredicted Y:\n", pre)
            print()
    print('Accuracy:', sess.run(accuracy, feed_dict = {X : x_data, Y : y_data}))

step: 0 cost: 1.39176 
predicted Y:
 [[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]

step: 5000 cost: 0.621105 
predicted Y:
 [[ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]

step: 10000 cost: 0.542751 
predicted Y:
 [[ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]

step: 15000 cost: 0.491557 
predicted Y:
 [[ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]

step: 20000 cost: 0.448958 
predicted Y:
 [[ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]

Accuracy: 0.833333


# (번외 2) Optimizer 성능비교

- 위의 multivariable linear regression과 optimizer만 다르다. 
- 시작 지점이 모두 같기 때문에, step 0에서의 cost값이 모두 같다.
- 최적의 결과를 위해 각 optimizer 별로 learing rate를 다르게 줬다.

옵티마이저에 대해 알고 싶다면 다음의 링크를 참고하자.

*옵티마이저 안내서*
https://github.com/YBIGTA/Deep_learning/blob/master/RNN/nlp/%EC%9D%B4%EB%A1%A0/Tensorflow%20Optimizer%20%EC%95%88%EB%82%B4%EC%84%9C.md

# multivariable linear regression

## GradientDescent 

In [42]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)

train = optimizer.minimize(cost)

In [43]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(20001):
        cost_val, hypo_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
        if step%5000 == 0:
            print("step:", step, "cost:", cost_val, "\npredicted y:\n", hypo_val)

step: 0 cost: 68860.0 
predicted y:
 [[ -87.23231506]
 [ -91.4056015 ]
 [ -97.27399445]
 [-102.95302582]
 [ -68.74664307]]
step: 5000 cost: 2.44453 
predicted y:
 [[ 149.21354675]
 [ 185.96690369]
 [ 179.59849548]
 [ 197.8147583 ]
 [ 141.73757935]]
step: 10000 cost: 1.44062 
predicted y:
 [[ 150.24142456]
 [ 185.290802  ]
 [ 179.94970703]
 [ 197.78677368]
 [ 141.08848572]]
step: 15000 cost: 1.12916 
predicted y:
 [[ 150.58778381]
 [ 185.07862854]
 [ 180.08796692]
 [ 197.63685608]
 [ 141.02111816]]
step: 20000 cost: 0.916443 
predicted y:
 [[ 150.74908447]
 [ 184.990448  ]
 [ 180.16583252]
 [ 197.47177124]
 [ 141.09240723]]


기본템(?)의 한계인 것 같다.

## Adam 

In [34]:
optimizer = tf.train.AdamOptimizer(learning_rate=0.1)

train = optimizer.minimize(cost)

In [35]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(20001):
        cost_val, hypo_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
        if step%5000 == 0:
            print("step:", step, "cost:", cost_val, "\npredicted y:\n", hypo_val)

step: 0 cost: 68860.0 
predicted y:
 [[ -87.23231506]
 [ -91.4056015 ]
 [ -97.27399445]
 [-102.95302582]
 [ -68.74664307]]
step: 5000 cost: 0.122591 
predicted y:
 [[ 151.74658203]
 [ 184.47531128]
 [ 180.05627441]
 [ 196.45507812]
 [ 142.25134277]]
step: 10000 cost: 0.106063 
predicted y:
 [[ 151.75942993]
 [ 184.47709656]
 [ 180.20199585]
 [ 196.29104614]
 [ 142.27111816]]
step: 15000 cost: 0.104489 
predicted y:
 [[ 151.74183655]
 [ 184.48806763]
 [ 180.25094604]
 [ 196.25901794]
 [ 142.25230408]]
step: 20000 cost: 0.104351 
predicted y:
 [[ 151.74153137]
 [ 184.49746704]
 [ 180.27182007]
 [ 196.25576782]
 [ 142.25120544]]


역시 널리 쓰이는 optimizer답게 가장 많이 cost를 낮추었다.

## Adadelta

In [50]:
optimizer = tf.train.AdadeltaOptimizer(learning_rate=0.1)

train = optimizer.minimize(cost)

In [51]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(20001):
        cost_val, hypo_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
        if step%5000 == 0:
            print("step:", step, "cost:", cost_val, "\npredicted y:\n", hypo_val)

step: 0 cost: 68860.0 
predicted y:
 [[ -87.23231506]
 [ -91.4056015 ]
 [ -97.27399445]
 [-102.95302582]
 [ -68.74664307]]
step: 5000 cost: 18379.7 
predicted y:
 [[ 25.40249443]
 [ 43.85400391]
 [ 36.01847076]
 [ 42.14390564]
 [ 34.54243469]]
step: 10000 cost: 197.727 
predicted y:
 [[ 133.64881897]
 [ 173.83914185]
 [ 164.11549377]
 [ 181.58486938]
 [ 133.80302429]]
step: 15000 cost: 5.65246 
predicted y:
 [[ 147.61254883]
 [ 187.03881836]
 [ 178.96209717]
 [ 197.39855957]
 [ 143.35002136]]
step: 20000 cost: 0.99821 
predicted y:
 [[ 150.4889679 ]
 [ 185.18148804]
 [ 179.86529541]
 [ 197.54165649]
 [ 141.47080994]]


Adadelta는 gradient를 누적시키는 optimizer이다.

그러므로 과거의 data가 현재의 data에 영향을 준다는 것을 전제하고 있으므로 과거 data와 현재 data가 아무 관계가 없는 선형 모델에서 그렇게 좋지 않은 결과가 나온 것 같다.

## Momentum

In [56]:
optimizer = tf.train.MomentumOptimizer(1e-5, 0.5)

train = optimizer.minimize(cost)

다른 optimizer와 달리 momentum은 learing rate말고도 momentum이라는 것을 설정해 줘야 한다. (위의 예시에서는 두 번째 parameter)

In [57]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(20001):
        cost_val, hypo_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
        if step%5000 == 0:
            print("step:", step, "cost:", cost_val, "\npredicting y:\n", hypo_val)

step: 0 cost: 68860.0 
predicting y:
 [[ -87.23231506]
 [ -91.4056015 ]
 [ -97.27399445]
 [-102.95302582]
 [ -68.74664307]]
step: 5000 cost: 1.44058 
predicting y:
 [[ 150.24179077]
 [ 185.29051208]
 [ 179.94981384]
 [ 197.78691101]
 [ 141.08807373]]
step: 10000 cost: 0.916466 
predicting y:
 [[ 150.74916077]
 [ 184.99040222]
 [ 180.16584778]
 [ 197.47181702]
 [ 141.09231567]]
step: 15000 cost: 0.622517 
predicting y:
 [[ 150.93809509]
 [ 184.89830017]
 [ 180.27120972]
 [ 197.17822266]
 [ 141.28387451]]
step: 20000 cost: 0.441686 
predicting y:
 [[ 151.07244873]
 [ 184.83554077]
 [ 180.3495636 ]
 [ 196.94480896]
 [ 141.44667053]]


## RMSprop

In [58]:
optimizer = tf.train.RMSPropOptimizer(1e-3)

train = optimizer.minimize(cost)

In [59]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(20001):
        cost_val, hypo_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
        if step%5000 == 0:
            print("step:", step, "cost:", cost_val, "\npredicted y:\n", hypo_val)

step: 0 cost: 68860.0 
predicted y:
 [[ -87.23231506]
 [ -91.4056015 ]
 [ -97.27399445]
 [-102.95302582]
 [ -68.74664307]]
step: 5000 cost: 0.577169 
predicted y:
 [[ 150.92687988]
 [ 184.69987488]
 [ 179.82000732]
 [ 197.12867737]
 [ 141.41873169]]
step: 10000 cost: 0.198688 
predicted y:
 [[ 151.41647339]
 [ 184.44650269]
 [ 179.90222168]
 [ 196.57073975]
 [ 141.89382935]]
step: 15000 cost: 0.142456 
predicted y:
 [[ 151.58512878]
 [ 184.36265564]
 [ 179.93363953]
 [ 196.3480072 ]
 [ 142.09187317]]
step: 20000 cost: 0.133451 
predicted y:
 [[ 151.64553833]
 [ 184.33312988]
 [ 179.95223999]
 [ 196.26086426]
 [ 142.16299438]]


Adam 다음으로 성적이 제일 좋다.

Adadelta와 비슷하지만 훨씬 잘 나온다.

## Adagrad

In [60]:
optimizer = tf.train.AdagradOptimizer(1.5)

train = optimizer.minimize(cost)

In [61]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(20001):
        cost_val, hypo_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
        if step%5000 == 0:
            print("step:", step, "cost:", cost_val, "\npredicted y:\n", hypo_val)

step: 0 cost: 68860.0 
predicted y:
 [[ -87.23231506]
 [ -91.4056015 ]
 [ -97.27399445]
 [-102.95302582]
 [ -68.74664307]]
step: 5000 cost: 0.586276 
predicted y:
 [[ 150.99961853]
 [ 184.86265564]
 [ 179.92234802]
 [ 197.3021698 ]
 [ 141.54165649]]
step: 10000 cost: 0.238315 
predicted y:
 [[ 151.44346619]
 [ 184.62606812]
 [ 179.99736023]
 [ 196.8553772 ]
 [ 141.89830017]]
step: 15000 cost: 0.150578 
predicted y:
 [[ 151.62657166]
 [ 184.53460693]
 [ 180.02790833]
 [ 196.61959839]
 [ 142.11032104]]
step: 20000 cost: 0.127507 
predicted y:
 [[ 151.71615601]
 [ 184.49026489]
 [ 180.04751587]
 [ 196.49842834]
 [ 142.21551514]]


선형 모델에 적합한 특징답게, 선형 모델에서 우수한 성적이 나온다.

거의 Adam과 비슷하다.

한 가지 주의점은 optimizer별로 잘 되는 learing rate가 다르니 0.1씩이나 0.05씩 값을 조정해나가면서 찾는 게 좋은 것 같다.

초기 값이 뭐냐에 따라 써야하는 lr이 다른 것 같기도 하다. 

시작점이 어디냐에 따라서 모델이 local minmum이라는 함정에 빠질수도 그렇지 않을 수도 있기 때문이다...!

왠만하면 Adam을 쓰도록 하자...!

하지만 sparse data하고 과거의 데이터가 현재에도 영향을 미칠 때(자연어, 스피치, finance 등등) Adadelta도 시도해보자.